// This file was originally generated by the bivector.net tool,
// created by Steven De Keninck (enki).
// The original code is provided under a permissive license (assumed to be MIT or similar)
// allowing for modification and redistribution.
//
// Significant performance optimizations (Fluent Interface, ThreadStatic buffer)
// have been applied by Hirohito Arai.

// Written by a generator written by enki.
using System;
using UnityEngine;

namespace GeometricAlgebra4D
{
	[System.Serializable]
	public struct Bivector4D
	{
		public float xy, xz, xw, yz, yw, zw;
		public Bivector4D(float xy = 0, float xz = 0, float xw = 0, float yz = 0, float yw = 0, float zw = 0)
		{ this.xy = xy; this.xz = xz; this.xw = xw; this.yz = yz; this.yw = yw; this.zw = zw; }
		public static Bivector4D zero => new Bivector4D(0f, 0f, 0f, 0f, 0f, 0f);
		public static Bivector4D Rotxy => new Bivector4D(1f, 0f, 0f, 0f, 0f, 0f);
		public static Bivector4D Rotxz => new Bivector4D(0f, 1f, 0f, 0f, 0f, 0f);
		public static Bivector4D Rotxw => new Bivector4D(0f, 0f, 1f, 0f, 0f, 0f);
		public static Bivector4D Rotyz => new Bivector4D(0f, 0f, 0f, 1f, 0f, 0f);
		public static Bivector4D Rotyw => new Bivector4D(0f, 0f, 0f, 0f, 1f, 0f);
		public static Bivector4D Rotzw => new Bivector4D(0f, 0f, 0f, 0f, 0f, 1f);
		public float NormSq() => xy * xy + xz * xz + xw * xw + yz * yz + yw * yw + zw * zw;
		public Bivector4D Normalized()
		{
			float nSq = NormSq();
			if (nSq > 1e-12f) {
				float n = Mathf.Sqrt(nSq);
				return new Bivector4D(xy / n, xz / n, xw / n, yz / n, yw / n, zw / n);
			}
			return new Bivector4D();
		}
		public static float Dot(Bivector4D a, Bivector4D b) => a.xy * b.xy + a.xz * b.xz + a.xw * b.xw + a.yz * b.yz + a.yw * b.yw + a.zw * b.zw;
		public override string ToString(){return $"({xy}, {xz}, {xw}, {yz}, {yw}, {zw})";}
	}
	public class GA4D
	{
		public static float EPS = 1e-6f;
		[ThreadStatic]
		private static float[] _tempCalculationBuffer;
		private float[] _mVec = new float[16];

		public GA4D(float f = 0f, int idx = 0)
		{
			_mVec[idx] = f;
		}

		public float this[int idx]
		{
			get { return _mVec[idx]; }
			set { _mVec[idx] = value; }
		}
		public GA4D Set(GA4D other)
		{
			Array.Copy(other._mVec, this._mVec, 16);
			return this;
		}
		public GA4D Zero()
		{
			Array.Clear(this._mVec, 0, 16);
			return this;
		}
		// Convert Vector4 to GA4D
		public GA4D ConvertVectorToGA4D(Vector4 v)
		{
			this.Zero();
			this._mVec[1] = v.x;
			this._mVec[2] = v.y;
			this._mVec[3] = v.z;
			this._mVec[4] = v.w;
			return this;
		}
		public GA4D Reverse()
		{
			this[5] = -this[5];
			this[6] = -this[6];
			this[7] = -this[7];
			this[8] = -this[8];
			this[9] = -this[9];
			this[10] = -this[10];
			this[11] = -this[11];
			this[12] = -this[12];
			this[13] = -this[13];
			this[14] = -this[14];
			return this;
		}
		public GA4D Dual()
		{
			if (_tempCalculationBuffer == null)
			{
				_tempCalculationBuffer = new float[16];
			}
			var temp = _tempCalculationBuffer;
			Array.Copy(this._mVec, temp, 16);
			this._mVec[0] = temp[15];
			this._mVec[1] = temp[14];
			this._mVec[2] = -temp[13];
			this._mVec[3] = temp[12];
			this._mVec[4] = -temp[11];
			this._mVec[5] = -temp[10];
			this._mVec[6] = temp[9];
			this._mVec[7] = -temp[8];
			this._mVec[8] = -temp[7];
			this._mVec[9] = temp[6];
			this._mVec[10] = -temp[5];
			this._mVec[11] = -temp[4];
			this._mVec[12] = temp[3];
			this._mVec[13] = -temp[2];
			this._mVec[14] = temp[1];
			this._mVec[15] = temp[0]; 
			return this;
		}
		public GA4D Conjugate()
		{
			this[1] = -this[1];
			this[2] = -this[2];
			this[3] = -this[3];
			this[4] = -this[4];
			this[5] = -this[5];
			this[6] = -this[6];
			this[7] = -this[7];
			this[8] = -this[8];
			this[9] = -this[9];
			this[10] = -this[10];

			return this;
		}
		public GA4D Multiply(GA4D other)
		{
			if (_tempCalculationBuffer == null)
			{
				_tempCalculationBuffer = new float[16];
			}
			var tempResult = _tempCalculationBuffer;

			tempResult[0] = other[0] * this[0] + other[1] * this[1] + other[2] * this[2] + other[3] * this[3] + other[4] * this[4] - other[5] * this[5] - other[6] * this[6] - other[7] * this[7] - other[8] * this[8] - other[9] * this[9] - other[10] * this[10] - other[11] * this[11] - other[12] * this[12] - other[13] * this[13] - other[14] * this[14] + other[15] * this[15];
			tempResult[1] = other[1] * this[0] + other[0] * this[1] - other[5] * this[2] - other[6] * this[3] - other[7] * this[4] + other[2] * this[5] + other[3] * this[6] + other[4] * this[7] - other[11] * this[8] - other[12] * this[9] - other[13] * this[10] - other[8] * this[11] - other[9] * this[12] - other[10] * this[13] + other[15] * this[14] - other[14] * this[15];
			tempResult[2] = other[2] * this[0] + other[5] * this[1] + other[0] * this[2] - other[8] * this[3] - other[9] * this[4] - other[1] * this[5] + other[11] * this[6] + other[12] * this[7] + other[3] * this[8] + other[4] * this[9] - other[14] * this[10] + other[6] * this[11] + other[7] * this[12] - other[15] * this[13] - other[10] * this[14] + other[13] * this[15];
			tempResult[3] = other[3] * this[0] + other[6] * this[1] + other[8] * this[2] + other[0] * this[3] - other[10] * this[4] - other[11] * this[5] - other[1] * this[6] + other[13] * this[7] - other[2] * this[8] + other[14] * this[9] + other[4] * this[10] - other[5] * this[11] + other[15] * this[12] + other[7] * this[13] + other[9] * this[14] - other[12] * this[15];
			tempResult[4] = other[4] * this[0] + other[7] * this[1] + other[9] * this[2] + other[10] * this[3] + other[0] * this[4] - other[12] * this[5] - other[13] * this[6] - other[1] * this[7] - other[14] * this[8] - other[2] * this[9] - other[3] * this[10] - other[15] * this[11] - other[5] * this[12] - other[6] * this[13] - other[8] * this[14] + other[11] * this[15];
			tempResult[5] = other[5] * this[0] + other[2] * this[1] - other[1] * this[2] + other[11] * this[3] + other[12] * this[4] + other[0] * this[5] - other[8] * this[6] - other[9] * this[7] + other[6] * this[8] + other[7] * this[9] - other[15] * this[10] + other[3] * this[11] + other[4] * this[12] - other[14] * this[13] + other[13] * this[14] - other[10] * this[15];
			tempResult[6] = other[6] * this[0] + other[3] * this[1] - other[11] * this[2] - other[1] * this[3] + other[13] * this[4] + other[8] * this[5] + other[0] * this[6] - other[10] * this[7] - other[5] * this[8] + other[15] * this[9] + other[7] * this[10] - other[2] * this[11] + other[14] * this[12] + other[4] * this[13] - other[12] * this[14] + other[9] * this[15];
			tempResult[7] = other[7] * this[0] + other[4] * this[1] - other[12] * this[2] - other[13] * this[3] - other[1] * this[4] + other[9] * this[5] + other[10] * this[6] + other[0] * this[7] - other[15] * this[8] - other[5] * this[9] - other[6] * this[10] - other[14] * this[11] - other[2] * this[12] - other[3] * this[13] + other[11] * this[14] - other[8] * this[15];
			tempResult[8] = other[8] * this[0] + other[11] * this[1] + other[3] * this[2] - other[2] * this[3] + other[14] * this[4] - other[6] * this[5] + other[5] * this[6] - other[15] * this[7] + other[0] * this[8] - other[10] * this[9] + other[9] * this[10] + other[1] * this[11] - other[13] * this[12] + other[12] * this[13] + other[4] * this[14] - other[7] * this[15];
			tempResult[9] = other[9] * this[0] + other[12] * this[1] + other[4] * this[2] - other[14] * this[3] - other[2] * this[4] - other[7] * this[5] + other[15] * this[6] + other[5] * this[7] + other[10] * this[8] + other[0] * this[9] - other[8] * this[10] + other[13] * this[11] + other[1] * this[12] - other[11] * this[13] - other[3] * this[14] + other[6] * this[15];
			tempResult[10] = other[10] * this[0] + other[13] * this[1] + other[14] * this[2] + other[4] * this[3] - other[3] * this[4] - other[15] * this[5] - other[7] * this[6] + other[6] * this[7] - other[9] * this[8] + other[8] * this[9] + other[0] * this[10] - other[12] * this[11] + other[11] * this[12] + other[1] * this[13] + other[2] * this[14] - other[5] * this[15];
			tempResult[11] = other[11] * this[0] + other[8] * this[1] - other[6] * this[2] + other[5] * this[3] - other[15] * this[4] + other[3] * this[5] - other[2] * this[6] + other[14] * this[7] + other[1] * this[8] - other[13] * this[9] + other[12] * this[10] + other[0] * this[11] - other[10] * this[12] + other[9] * this[13] - other[7] * this[14] + other[4] * this[15];
			tempResult[12] = other[12] * this[0] + other[9] * this[1] - other[7] * this[2] + other[15] * this[3] + other[5] * this[4] + other[4] * this[5] - other[14] * this[6] - other[2] * this[7] + other[13] * this[8] + other[1] * this[9] - other[11] * this[10] + other[10] * this[11] + other[0] * this[12] - other[8] * this[13] + other[6] * this[14] - other[3] * this[15];
			tempResult[13] = other[13] * this[0] + other[10] * this[1] - other[15] * this[2] - other[7] * this[3] + other[6] * this[4] + other[14] * this[5] + other[4] * this[6] - other[3] * this[7] - other[12] * this[8] + other[11] * this[9] + other[1] * this[10] - other[9] * this[11] + other[8] * this[12] + other[0] * this[13] - other[5] * this[14] + other[2] * this[15];
			tempResult[14] = other[14] * this[0] + other[15] * this[1] + other[10] * this[2] - other[9] * this[3] + other[8] * this[4] - other[13] * this[5] + other[12] * this[6] - other[11] * this[7] + other[4] * this[8] - other[3] * this[9] + other[2] * this[10] + other[7] * this[11] - other[6] * this[12] + other[5] * this[13] + other[0] * this[14] - other[1] * this[15];
			tempResult[15] = other[15] * this[0] + other[14] * this[1] - other[13] * this[2] + other[12] * this[3] - other[11] * this[4] + other[10] * this[5] - other[9] * this[6] + other[8] * this[7] + other[7] * this[8] - other[6] * this[9] + other[5] * this[10] + other[4] * this[11] - other[3] * this[12] + other[2] * this[13] - other[1] * this[14] + other[0] * this[15];
			Array.Copy(tempResult, this._mVec, 16);
			return this;
		}
		public GA4D Wedge(GA4D other)
		{
			if (_tempCalculationBuffer == null)
			{
				_tempCalculationBuffer = new float[16];
			}
			var tempResult = _tempCalculationBuffer;
			tempResult[0] = other[0] * this[0];
			tempResult[1] = other[1] * this[0] + other[0] * this[1];
			tempResult[2] = other[2] * this[0] + other[0] * this[2];
			tempResult[3] = other[3] * this[0] + other[0] * this[3];
			tempResult[4] = other[4] * this[0] + other[0] * this[4];
			tempResult[5] = other[5] * this[0] + other[2] * this[1] - other[1] * this[2] + other[0] * this[5];
			tempResult[6] = other[6] * this[0] + other[3] * this[1] - other[1] * this[3] + other[0] * this[6];
			tempResult[7] = other[7] * this[0] + other[4] * this[1] - other[1] * this[4] + other[0] * this[7];
			tempResult[8] = other[8] * this[0] + other[3] * this[2] - other[2] * this[3] + other[0] * this[8];
			tempResult[9] = other[9] * this[0] + other[4] * this[2] - other[2] * this[4] + other[0] * this[9];
			tempResult[10] = other[10] * this[0] + other[4] * this[3] - other[3] * this[4] + other[0] * this[10];
			tempResult[11] = other[11] * this[0] + other[8] * this[1] - other[6] * this[2] + other[5] * this[3] + other[3] * this[5] - other[2] * this[6] + other[1] * this[8] + other[0] * this[11];
			tempResult[12] = other[12] * this[0] + other[9] * this[1] - other[7] * this[2] + other[5] * this[4] + other[4] * this[5] - other[2] * this[7] + other[1] * this[9] + other[0] * this[12];
			tempResult[13] = other[13] * this[0] + other[10] * this[1] - other[7] * this[3] + other[6] * this[4] + other[4] * this[6] - other[3] * this[7] + other[1] * this[10] + other[0] * this[13];
			tempResult[14] = other[14] * this[0] + other[10] * this[2] - other[9] * this[3] + other[8] * this[4] + other[4] * this[8] - other[3] * this[9] + other[2] * this[10] + other[0] * this[14];
			tempResult[15] = other[15] * this[0] + other[14] * this[1] - other[13] * this[2] + other[12] * this[3] - other[11] * this[4] + other[10] * this[5] - other[9] * this[6] + other[8] * this[7] + other[7] * this[8] - other[6] * this[9] + other[5] * this[10] + other[4] * this[11] - other[3] * this[12] + other[2] * this[13] - other[1] * this[14] + other[0] * this[15];
			Array.Copy(tempResult, this._mVec, 16);
			return this;
		}
		
		//Scalar division
		public GA4D Divide(float scalar)
		{
			if (Mathf.Abs(scalar) < 1e-12f) return this;
			float inv_scalar = 1.0f / scalar;
			for (int i = 0; i < 16; i++) this[i] *= inv_scalar;
			return this;
		}

		private static GA4D _temp_self = new();
		private static GA4D _temp_conjugate = new();
		private static GA4D _temp_blade = new();

		private static GA4D _ga_v0 = new();
		private static GA4D _ga_v1 = new();
		private static GA4D _ga_v2 = new();
		private static GA4D _ga_v3 = new();
		private static GA4D _ga_rotor = new();
		public float Norm()
		{
			_temp_conjugate.Set(this).Conjugate();
			_temp_self.Set(this).Multiply(_temp_conjugate);
			return Mathf.Sqrt(Mathf.Abs(_temp_self[0]));
		}
		
		//Generate a rotor from two vectors
		public GA4D CreateRotorWithVector(Vector4 v0, Vector4 v1,float angleDeg)
		{
			_ga_v0.ConvertVectorToGA4D(v0);
			_ga_v1.ConvertVectorToGA4D(v1);
			_temp_self.Set(_ga_v0).Wedge(_ga_v1);

			_temp_blade.Zero();
			_temp_blade[5] = _temp_self[5];
			_temp_blade[6] = _temp_self[6];
			_temp_blade[7] = _temp_self[7];
			_temp_blade[8] = _temp_self[8];
			_temp_blade[9] = _temp_self[9];
			_temp_blade[10] = _temp_self[10];

			float norm = _temp_blade.Norm();
			if (norm > EPS)
			{
				_temp_blade.Divide(norm);
			}
			float halfAngleRad = (angleDeg % 360) * Mathf.Deg2Rad * -0.5f;
			float c = Mathf.Cos(halfAngleRad);
			float s = Mathf.Sin(halfAngleRad);
    
			this[0] = c;
			this[5] = s * _temp_blade[5];
			this[6] = s * _temp_blade[6];
			this[7] = s * _temp_blade[7];
			this[8] = s * _temp_blade[8];
			this[9] = s * _temp_blade[9];
			this[10] = s * _temp_blade[10];
			return this;
		}

		//Generate rotors from bivectors and Euler angles
		public GA4D CreateRotor(Bivector4D blade, float angleDeg)
		{
			if (blade.NormSq() < EPS)
			{
				this.Zero(); 
				this[0] = 1f;
				return this;
			}
    
			float halfAngleRad = (angleDeg % 360) * Mathf.Deg2Rad * -0.5f;
			float c = Mathf.Cos(halfAngleRad);
			float s = Mathf.Sin(halfAngleRad);
    
			Bivector4D b_norm = blade.Normalized();
    
			this.Zero();
			this[0] = c;
			this[5] = s * b_norm.xy;
			this[6] = s * b_norm.xz;
			this[7] = s * b_norm.xw;
			this[8] = s * b_norm.yz;
			this[9] = s * b_norm.yw;
			this[10] = s * b_norm.zw;
			return this;
		}

		//Rotor spinning vector
		public static void RotateVector(in Vector4 v0, GA4D rotor, out Vector4 result)
		{
			_ga_v0.ConvertVectorToGA4D(v0);
			_ga_rotor.Set(rotor).Reverse();
			_ga_v1.Set(rotor).Multiply(_ga_v0).Multiply(_ga_rotor);

			result.x = _ga_v1[1];
			result.y = _ga_v1[2];
			result.z = _ga_v1[3];
			result.w = _ga_v1[4];
		}

		//Wedge product for finding normals
		public static Vector4 Cross4D(in Vector4 v0, in Vector4 v1, in Vector4 v2)
		{
			_ga_v0.ConvertVectorToGA4D(v0);
			_ga_v1.ConvertVectorToGA4D(v1);
			_ga_v2.ConvertVectorToGA4D(v2);
			_ga_v0.Wedge(_ga_v1).Wedge(_ga_v2).Dual();

			// 3. Œ‹‰Ê‚ð•Ô‚·
			return new Vector4(_ga_v0[1], _ga_v0[2], _ga_v0[3], _ga_v0[4]);
		}

		//Calculate the four-dimensional volume created by four independent vectors
		public static float Volume4D(in Vector4 v0, in Vector4 v1, in Vector4 v2, in Vector4 v3)
		{
			_ga_v0.ConvertVectorToGA4D(v0);
			_ga_v1.ConvertVectorToGA4D(v1);
			_ga_v2.ConvertVectorToGA4D(v2);
			_ga_v3.ConvertVectorToGA4D(v3);
			_ga_v0.Wedge(_ga_v1).Wedge(_ga_v2).Wedge(_ga_v3).Dual();
			return _ga_v0[0];
		}
	}
}